\documentclass{article}
\usepackage[sc]{mathpazo}
\usepackage[T1]{fontenc}
\usepackage{cite}
\usepackage{geometry}
\geometry{verbose,tmargin=2.5cm,bmargin=2.5cm,lmargin=2.5cm,rmargin=2.5cm}
\setcounter{secnumdepth}{2}
\setcounter{tocdepth}{2}
\usepackage{url}
\usepackage[unicode=true,pdfusetitle,
 bookmarks=true,bookmarksnumbered=true,bookmarksopen=true,bookmarksopenlevel=2,
 breaklinks=false,pdfborder={0 0 1},backref=false,colorlinks=false]
 {hyperref}
\hypersetup{
 pdfstartview={XYZ null null 1}}
\usepackage{breakurl}

\usepackage{setspace}
\usepackage{relsize}

\bibliographystyle{plos2009}

\begin{document}

\title{Identification of variables associated with geographic
  movements of PEDV with a novel regularized regression approach}

\author{Eamon O'Dea}

\maketitle

\section*{Introduction}

We build on the work of Refs.~\cite{lemey2014,magee2014}.

\section*{Methods}

\section*{Results}

<<load-results,include=FALSE>>=

# load("../work/results.RData")

answer <- 7

@ 

We find \Sexpr{answer} important variables.

\section*{Discussion}


\bibliography{pedv}


\end{document}
