
* outline

** the main point

Introduction of a regularization approach to efficiently fitting
regression models of the transition rates of discrete traits and
verification that locations of molecular samples may be modeled this
way to infer migration parameters

** the narrative arc

- summary of the new approach
- background on pedv
- phylogenetic fit of PEDV data
 - high diversity by time of first known outbreak
- simulated likelihood ratio test of effect of flows
 - reject null 
- stability selection of predictors of migration rates
 - balance sheet variables stable
- simulation study showing that modeling approach is reasonable
 - including number of samples can bias estimates

** what we did

1. developed algorithm for estimating regularization paths for
   discrete trait models 
2. BEAST analysis of whole-genome PEDV sequences
2.1 Compare prior and posterior distribution of root node times
3. stability selection on predictors of PEDV movement
4. examine distribution of estimates with simulation of traits conditional on tree
4.1 test whether bias of simulated likelihood is greater than
uncertainty in estimates
5. examine distribution of estimates with simulation of trees
   conditional on traits
   
** why we did it

1. To improve the speed of fitting phylogeographic models to the point
   where simulation studies were practical and provide a faster
   alternative to previously used Bayesian approaches , we developed
   an algorithm for estimating regularization paths for regression
   models of transition rates in discrete trait models of molecular
   evolution.
2. To estimate the distribution of phylogenies consistent with the
   molecular sequences of PEDV collected, we performed a BEAST
   analysis.
2.1 To determine whether multiple introductons or undetected
circulation of PEDV was consistent with the data, we compared prior
and posterior distributions of the MRCA for two clades.
3. To determine what variables might be associated with the movement
   of PEDV between states, we performed stability selection.
4. To estimate uncertainty of estimates due to the random variation
   inherent in the model, we generated parametric bootstrap confidence
   intervals conditional on the estimated trees.
4.1 To determine if a sufficient number of trees were averaged over in
the likelihood calculation, we tested whether the bias was significant
given the uncertainty of the extimes 
5. To estimate how ignoring the dependence of geographic traits and
   coalescence rates may be biasing our estimates and determine if our
   estimates were self-consistent, we fit our model to data simulated
   in a structured coalescent model, both with and without a
   previously used method of bias correction.

** what resulted

1. A tested algorithm and an R implementation for estimating
   regularization paths for discrete trait models

x := model parameters
\mu := prox parameter
G := Hessian in quadratic model to full likelihood
r := ratio of decrease in likelihood to decrease in quadratic model
considered sufficient
k := iteration counter
a := parameter that determine how accuracy of subproblem solution
should grow with k
beta := parameter that determine how to update prox parameter when necessary

algorithm: based on Tang and Scheinberg
1. choose 0 < r \leq 1, a > 0, x^0
for k in 0, 1, 2, ... do
  choose 0 < \mu_k, \theta_k > 0, G_k positive semidefinite
  Find H_k = G_k + 1 / (2 \mu_k) I and x^{k + 1} by applying prox
  parameter update with randomized coordinate descent
  
BFGS instead of L-BFGS
keep hessian est between lambda but allow for larger neighborhood to
be searched


2. Posterior distribution for MRCAs (figure)
3. Stability paths and a set of variables considered stable (figure)
4. percentile confidence intervals for parameter estimates with
   pre-specified models (knitr output)
4.1 determination that number of trees was adequate (knitr output)
5. determination that bias was lower than without attempted
   correction, and an explanation for the observed nonexponentiality
   of coalescent intervals (knitr output)

** findings

- regularized regression can be used as lower-complexity alternative to the
Bayesian stochastic search variable selection used previously
- model estimates are self-consistent with data being generated by
  more realistic structured coalescent 
  - surprisingly, geographic attributes may be modeled as discrete
    traits in situations such as our application.: 5 
  - when performing phylogeographic analyses, trying to correct for
    unequal sampling efforts can be counterproductive.: 5
- integrating over a small number of trees may be adequate to capture the
  phylogenetic uncertainty in a phylogeographic model: 4.1
- balance sheet variables and flows are of modeling value for PEDV spread
 - directed flows are correlated with transition rates: 4
 - balance sheet variables are relevant variables: 3

** introduction draft
*** establishing a research territory
**** centrality
- better understanding of patterns of disease spread could improve
  control measures

- amount of sequence data likely to increase as technology becomes
  cheaper
 - molecular methods can perform well when other surveillance methods
   are subject to bias
- applications exist outside of disease for understanding species
  migration dispersal
- large number of studies have used phylogeographic models
**** review of methodolgical literature
- parsimony methods
- BEAST phylogeogrphraphic method with BSSVS
- continuous diffusion
- minimum spanning tree methods
 - potn
 - jombart et al.
- structured coalescent 
 - STRUCTURE and 
 - PLoS genetics 
**** review of applications
- papers introducing method
- US swine paper
- global swine paper
- influenza and air travel paper
- etc.

*** establishing a niche

- regularization approach not considered as alternative to BSSVS
- conditions under which geography may be modeled as as a discrete trait disputed
- ability of including number of samples as predictors to account for
  sampling bias unstudied

*** occupying the niche

 The purpose of this paper is to introduce a regularization approach
 to fitting discrete trait models and also to further demonstrate that
 they can provide accurate estimates of parameters for how a pathogen
 moves between areas.

** problem items

1. systematic comparison of regularization approach to BSSVS method
   not presented
2. proof not presented for results that bias correction may backfire
3. analytic results not presented for when geographic traits may be
   modeled independently of coalescent process

** responses to problems

1-3: Further analysis and simulation can establish the generality of our
findings. However, we have demonstrated that under at least one
realistic scenario are findings are valid.

** conclusion paragraph
   
We have introduced a new approach to fitting phylogeographic models
and demonstrated its usefulness for understanding the spread of a
recent emerging pathogen of livestock. We have found that, although
the modeling framework employed neglects to account for the spatial
distribution of lineages on coalescence rates, it can for data
simulated with the estimated parameters perform well. Clearly there
are some phylogeographic conditions under which the proposed approach
is valid and may be preferred for its speed, and simulation can be
used to assess performance for any particular condition. The question
we defer to future work is therefore not if this approach may be
usefully applied in phylogeography, but when.

** purpose sentence for each paragraph
** splice in figures
** opening and conclusion for each paragraph
** fill in supporting sentences

* Submission questions

** List significant discoveries reported in this manuscript, if any. (Not more than 150 words)

- balance sheet variable are stable predictors of the movement of PEDV
- phylogenetic modeling suggests multiple strands of PEDV were present
  before the first reported us outbreak

** List significant methodological or theoretical advances reported, if any. (Not more than 150 words)  ￼

- method to determine number of phylogenetic trees to necessary to average over in
  phylogeographic analysis
- demonstration of how previous practice of including number of
  samples as predictors can introduce bias
- new method has lower complexity than previous MCMC methods and thereby
  makes practical simulation tests of performance for specific
  applications 
- simulations show that that the estimated parameters are accurate for
  a structured coalescent model for the parameters that we estimated
  in our application to real data, while previous work has raised
  concern about whether geographic attributes may be modeled as
  discrete traits

** List significant new or updated tools or resources reported, if any. (Not more than 150 words)  ￼

- algorithms for fitting phylogeographic regression models with
  elastic net penalties, which exploits warm-starts to efficiently  fit
  models along a regularization path
- R scripts with functions implementing these algorithms available
  online at github 

** Describe how this work will have broad impact on science or on the community. (Not more than 150 words)  ￼

- Phylogeographic analyses are increasingly being used to understand
  how pathogens are spreading with increasing larger data sets, and
  some have raised concerns about the validity of the models
  used. This work describes an established statistical approach widely
  used in other domains that should scale better than some current
  phylogeographic approaches and provides a practical algorithm
  implementing it. We further show that for the parameters we
  estimated from a real data set, the method can recover similar
  parameters from simulated data and that including the number of
  samples as predictors, although done in several previous analyses,
  is not necessary and in fact likely to bias estimates. In short, we
  provide a faster way of performing phylogeogrpahic anlayses, which
  should permit larger-scale analyses and simulation studies of the
  statistical properties of the results, and demonstrate both of these
  activities with an application to a pathogen of recent economic
  consequence.
  
  
   
** Any other relevant information you wish to provide. (Not more than 150 words)
