#!/bin/bash

set -e

dtag="v2015.03.30"
topd=$(pwd)
tstamp=$(date +%Y-%m-%d_%H-%M-%S)
rnd=$RANDOM
wkdir="${topd}/work-${tstamp}-${rnd}"
ddir="${topd}/data"
sdir="${topd}/src"
hdir="/root"

docker run -it -v ${ddir}:${hdir}/data:ro \
       -v ${sdir}:${hdir}/src:ro \
       -v ${wkdir}:${hdir}/work \
       eamon/2015phylo:${dtag} /bin/bash

user=$(id -u)
group=$(id -g)

echo " Currently, $wkdir and its contents are always owned by root, so you might want to"
echo "    sudo chown -hR ${user}:${group} $wkdir "
