#!/bin/bash

set -e

dtag="v2015.08.16"
topd=$(pwd)
tstamp=$(date +%Y-%m-%d_%H-%M-%S)
rnd=$RANDOM
wkdir="${topd}/work-${tstamp}-${rnd}"
ddir="${topd}/data"
sdir="${topd}/src"
hdir="/root"
nproc=$(nproc)

docker run -v ${ddir}:${hdir}/data:ro \
       -v ${sdir}:${hdir}/src:ro \
       -v ${wkdir}:${hdir}/work \
       eamon/2015phylo:${dtag} /bin/bash -c "cd /root/work && nice -n 19 make -j $nproc -f /root/src/Makefile"

echo "Currently, $wkdir and its contents are always owned by root, so you might want to"
user=$(id -u)
group=$(id -g)
echo "     sudo chown -hR ${user}:${group} $wkdir "
