#!/bin/bash

set -e

topd=$(pwd)
wkdir="${topd}/work-sshd"
ddir="${topd}/data"
sdir="${topd}/src"
hdir="/root"

docker run -d -p 49153:22 -v ${ddir}:${hdir}/data:ro \
       -v ${sdir}:${hdir}/src:ro \
       -v ${wkdir}:${hdir}/work \
       --name 2015phylo_sshd eamon/2015phylo:v2013.03.26

user=$(id -u)
group=$(id -g)
